org: preiskampf
app: scrape-prices
service: scrape-prices

frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs20.x
    profile: "private_juelz"

functions:
    scrapeLidl:
        handler: src/handler.scrapeLidl
        timeout: 900
        events:
            - schedule:
                rate: cron(0 0 * * ? *) # every midnight
                enabled: false
    scrapeLidlSitemap:
        handler: src/handler.scrapeLidlSitemap
        timeout: 900
        events:
            - schedule:
                rate: cron(0 0 * * ? *)
                enabled: true
    scrapeAldiSued:
        handler: src/handler.scrapeAldiSued
        timeout: 900
        events:
            - schedule:
                rate: cron(0 0 * * ? *) # every midnight
                enabled: false
    scrapeAldiSuedSitemap:
        handler: src/handler.scrapeAldiSuedSitemap
        timeout: 900
        events:
            - schedule:
                rate: cron(0 1 * * ? *)
                enabled: true
    scrapeAldiNord:
        handler: src/handler.scrapeAldiNord
        timeout: 900
        events:
            - schedule:
                rate: cron(0 0 * * ? *) # every midnight
                enabled: false
    scrapeAldiNordSitemap:
        handler: src/handler.scrapeAldiNordSitemap
        timeout: 900
        events:
            - schedule:
                rate: cron(0 2 * * ? *)
                enabled: true

custom:
    esbuild:
        bundle: true
        minify: false

plugins:
    - serverless-esbuild
    - serverless-offline